function printStats(stats,info)
% takes in a stats structure and prints the results 
% in the display and in to a text file.


fileName        = strcat(info.savePath,info.Analysis);

diary(fileName)
%% group stats
disp(sprintf('Statistics for %s\n', info.Analysis))
disp(sprintf('Group Scores\n'))
disp(table(stats.groupScores(1,:)', ...
	stats.groupScores(2,:)', ...
	stats.groupScores(3,:)',...
	'rownames',info.rownames, ...
	'variablenames',info.groupNames))


disp(sprintf('Group PVals\n'))
disp(table(stats.groupPVals(1,:)', ...
	stats.groupPVals(2,:)', ...
	stats.groupPVals(3,:)',...
	'rownames',info.rownames, ...
	'variablenames',info.groupNames))

%% interaction stats
varNames = cell(stats.nCombs,1);
for iComb = 1:stats.nCombs
	varNames{iComb} = strcat(info.groupNames{stats.GroupCombs(iComb,1)},...
		'_',info.groupNames{stats.GroupCombs(iComb,2)});
end
disp(sprintf('Interaction Scores\n'))
disp(table(stats.groupScores(1,:)', ...
	stats.groupScores(2,:)', ...
	stats.groupScores(3,:)',...
	'rownames',info.rownames, ...
	'variablenames',varNames))


disp(sprintf('Group PVals\n'))
disp(table(stats.groupPVals(1,:)', ...
	stats.groupPVals(2,:)', ...
	stats.groupPVals(3,:)',...
	'rownames',info.rownames, ...
	'variablenames',varNames))
%%
diary